### ISSUE TITLE
렌딩 페이지

### ISSUE THREAD

**Issue by yeona813** [WhatToDo6/WhatToDo#41]
### TODO

- [x] '로고 버튼'을 클릭하면 / 페이지로 이동합니다.
- [x] '로그인' 버튼을 클릭하면 /login 페이지로 이동합니다.
- [x] '회원가입' 버튼을 클릭하면 /signup 페이지로 이동합니다.
- [x] 로그인이 되어있으면 /dashboard/{첫번째 dashboardid} 로 이동합니다
