### ISSUE TITLE
대시보드 생성 모달 적용

### ISSUE THREAD

**Issue by innerstella** [WhatToDo6/WhatToDo#58]
### TODO
- [x] '+' 버튼을 클릭하면 대시보드 생성 모달이 나타납니다.
- [x] 대시보드 생성 모달에서 대시보드 이름과 색을 선택해야 '생성' 버튼이 활성화가 됩니다.
- [ ] 대시보드 '생성'버튼을 누르면 대시보드가 생성이 되고 /dashboard/{dashboardid} 로 이동합니다

![image](https://github.com/WhatToDo6/WhatToDo/assets/77491430/5b997aaa-4100-4806-98a7-eca77b8adc32)
