### ISSUE TITLE
할 일 생성 모달 적용

### ISSUE THREAD

**Issue by innerstella** [WhatToDo6/WhatToDo#61]
### TODO

- [x] 모든 input이 채워지면 '생성' 버튼이 활성화 됩니다.
- [x] 담당자는 드롭다운으로 초대받은 인원만 고를 수 있습니다.
- [x] 이미지는 최대 1개입니다.
- [x] 태그 색상은 랜덤입니다.
- [x] '생성' 버튼을 클릭하면 해당 컬럼 하단에 할 일 카드가 생깁니다.
- [x] 날짜 입력 라이브러리를 사용해서 입력을 받아주세요

![image](https://github.com/WhatToDo6/WhatToDo/assets/77491430/c1efd75e-e93b-4180-bd10-edc443323cad)
