### ISSUE TITLE
칼럼 수정 모달 적용

### ISSUE THREAD

**Issue by innerstella** [WhatToDo6/WhatToDo#63]
### TODO

- [ ] 삭제하기' 버튼을 누르면 “컬럼의 모든 카드가 삭제됩니다” 경고창을 보여줍니다.
- [ ] '삭제’ 버튼을 누르면 해당 컬럼의 모든 할 일 카드들이 삭제가 됩니다.
- [x] 수정할 이름을 넣고 '변경'버튼을 누르면 컬럼 이름이 수정됩니다.

![image](https://github.com/WhatToDo6/WhatToDo/assets/77491430/1f12f3b8-8c84-438d-963f-4e73ecfb527b)
