### ISSUE TITLE
로그인 

### ISSUE THREAD

**Issue by innerstella** [WhatToDo6/WhatToDo#7]
### test 계정
{
"email": "[test@whattodo.com](mailto:test@whattodo.com)",
"nickname": "test",
"password": "123456789"
}

### TODO

- [x] 로고 버튼'을 클릭하면 / 페이지로 이동합니다.
- [x] '회원가입하기' 버튼을 클릭하면 /signup 페이지로 이동합니다.
- [x] 유효한 이메일과 비밀번호를 입력하고 '로그인' 버튼을 클릭하면 /mydashboard 페이지로 이동합니다.
- [x] 로그인 페이지에는 네비게이션바가 없습니다.
- [ ] 비밀번호가 틀릴 경우 “비밀번호가 일치하지 않습니다.” 경고 창을 보여줍니다.
- [x] 눈 모양 아이콘을 누르면 비밀번호를 숨기거나 나타낼 수 있습니다.
- [x] 이메일 input에서 focus out 일 때, 값이 이메일 형식이 아닐 경우 input에 빨강색 테두리와 아래에 “이메일 형식으로 작성해 주세요.” 빨강색 에러 메세지가 보입니다.
- [x] 비밀번호 input에서 focus out 일 때, 비밀번호 길이가 8자 미만일때 input에 빨강색 테두리와 아래에 “8자 이상 작성해 주세요.” 빨강색 에러 메세지가 보입니다.
- [x] 로그인 성공시 엑세스 토큰이 발급됩니다.

### 기타

- [x] 로그인 버튼 공통 컴포넌트로 교체
- [x] react-hook-form

**Comment by innerstella** [comment]
### accessToken 

1. 웹 브라우저의 메모리 또는 세션 스토리지: 웹 애플리케이션의 경우, access token을 웹 브라우저의 메모리에 저장하거나 세션 스토리지에 저장할 수 있습니다. 이렇게 하면 클라이언트 측에서 access token을 안전하게 보관할 수 있습니다. 하지만 XSS(Cross-Site Scripting) 공격에 취약할 수 있으므로 주의가 필요합니다.

2. HTTP Only 쿠키: 서버가 HTTP Only 쿠키를 사용하여 access token을 클라이언트에게 전달할 수 있습니다. 이 방법은 XSS 공격을 완화할 수 있습니다. 하지만 CSRF(Cross-Site Request Forgery) 공격에 취약할 수 있으므로 적절한 방어 메커니즘이 필요합니다.

3. 로컬 스토리지 또는 쿠키: 클라이언트 측에서 access token을 로컬 스토리지 또는 쿠키에 저장할 수 있습니다. 이러한 방법은 쉽게 구현할 수 있지만, XSS 공격에 취약할 수 있으므로 보안에 주의해야 합니다.

4. 메모리: 앱이나 서비스가 메모리에 access token을 저장하는 것도 가능합니다. 하지만 앱이나 서비스가 종료될 때 access token이 손실되므로 재인증이 필요할 수 있습니다.

**Comment by innerstella** [comment]
### 기획과 API 명세서의 불일치

#### 기획
- 비밀번호가 틀릴 경우 “비밀번호가 일치하지 않습니다.” 경고 창을 보여줍니다.

#### API 명세서
- 로그인 실패 시, 이메일 형식에 대한 오류와 존재하지 않는 유저에 대한 오류만 검증할 뿐 비밀번호 일치 여부에 대한 검증은 진행되지 않음

### 나의 결정
- API 명세서를 따름
