### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by innerstella** [WhatToDo6/WhatToDo#8]
### TODO

- [x] '로고 버튼'을 클릭하면 / 페이지로 이동합니다.
- [x] '로그인하기' 버튼을 클릭하면 /login 페이지로 이동합니다.
- [x] 닉네임 Input에서 focus out 일 때, 값이 열 자 이하가 아닐 경우 닉네임 input에 빨간색 테두리와 아래에 “열 자 이하로 작성해주세요.” 빨간색 에러 메세지가 보입니다. #27 
- [x] 이메일 input에서 focus out 일 때, 값이 이메일 형식이 아닐 경우 이메일 input에 빨강색 테두리와 아래에 “이메일 형식으로 작성해 주세요.” 빨강색 에러 메세지가 보입니다.
- [x] 비밀번호 input에서 focus out 일때 비밀번호 input 값 길이가 8자이상이 아닐 경우 비밀번호 input에 빨간색 테두리와 아래에 “8자 이상 입력해주세요.” 빨강색 에러 메세지가 보입니다.
- [x] 비밀번호 확인 input에서 focus out 일 때 비밀번호 input 값과 비밀번호 확인 input 값이 다를 경우 비밀번호 확인 input에 빨간색 테두리와 아래에 “비밀번호가 일치하지 않습니다.” 빨강색 에러 메세지가 보입니다.
- [x] 모든 input 창이 채워지고 에러 메세지가 없는 상태에서 이용약관에 체크가 되면 '가입하기' 버튼이 활성화가 됩니다.
- [ ] #30
- [x] 활성화된 '가입하기' 버튼을 누르면 “가입이 완료되었습니다” alert 창을 보여주고 /login 페이지로 이동합니다.

### 기타

- [x] 회원가입 버튼 공통 컴포넌트로 교체
- [x] axios 세팅
- [x] react-hook-form
