### ISSUE TITLE
계정관리 리팩토링

### ISSUE THREAD

**Issue by yeona813** [WhatToDo6/WhatToDo#96]
### TODO

- [x] BackButton 컴포넌트로 교체
- [x] 닉네임 input 너비 수정
- [x] 비밀번호 input 눈 모양 아이콘 반응형
- [x] classname 수정
